"""FastAI framework package root."""

from .ai_app import AIApp, ai_route
from .client import FastAIClient, create_fastai_client
from .config import (
	AuthConfig,
	FastAIConfig,
	IngestionConfig,
	LLMConfig,
	RetrievalConfig,
	RuntimeConfig,
	VectorStoreConfig,
)
from .ingestion import (
	ChunkEmbeddingResult,
	EmbeddingAdapter,
	LiteLLMEmbeddingAdapter,
	create_embedding_adapter,
)
from .plugin import get_fastai_router, mount_fastai_router
from .sdk import FastAI
from .storage import (
	DEFAULT_VECTOR_DIMENSION,
	Base,
	ChunkModel,
	ChunkRecord,
	ChunkRepository,
	DocumentModel,
	DocumentRecord,
	DocumentRepository,
	EmbeddingModel,
	EmbeddingRecord,
	EmbeddingRepository,
	MongoDBAtlasVectorAdapter,
	PgVectorAdapter,
	PostgresChunkRepository,
	PostgresDocumentRepository,
	PostgresEmbeddingRepository,
	PostgresRepositoryBundle,
	QdrantVectorAdapter,
	RouteDefinitionModel,
	StorageSessionManager,
	VectorQueryMatch,
	VectorStoreAdapter,
	create_postgres_repositories,
	select_vector_adapter,
)

__all__ = [
	"AIApp",
	"AuthConfig",
	"FastAI",
	"FastAIClient",
	"FastAIConfig",
	"IngestionConfig",
	"LLMConfig",
	"ChunkEmbeddingResult",
	"EmbeddingAdapter",
	"LiteLLMEmbeddingAdapter",
	"RetrievalConfig",
	"RuntimeConfig",
	"VectorStoreConfig",
	"ChunkRecord",
	"ChunkModel",
	"ChunkRepository",
	"DEFAULT_VECTOR_DIMENSION",
	"DocumentRecord",
	"DocumentModel",
	"DocumentRepository",
	"EmbeddingRecord",
	"EmbeddingModel",
	"EmbeddingRepository",
	"Base",
	"MongoDBAtlasVectorAdapter",
	"PgVectorAdapter",
	"PostgresChunkRepository",
	"PostgresDocumentRepository",
	"PostgresEmbeddingRepository",
	"PostgresRepositoryBundle",
	"QdrantVectorAdapter",
	"RouteDefinitionModel",
	"StorageSessionManager",
	"VectorQueryMatch",
	"VectorStoreAdapter",
	"__version__",
	"ai_route",
	"create_embedding_adapter",
	"create_postgres_repositories",
	"create_fastai_client",
	"get_fastai_router",
	"mount_fastai_router",
	"select_vector_adapter",
]

__version__ = "0.1.0"
